Ticket5494
ISISComputingGroup/EPICS-IOC_Test_Framework pull request #382
Opened 2020-10-28 17:11 UTC by Alistair-McGann-Tessella

# Ticket
https://github.com/ISISComputingGroup/IBEX/issues/5494

2020-11-06 10:52 UTC, JamesKingWork submitted a review, later dismissed

2020-11-06 10:52 UTC, JamesKingWork commented on tests/tizr.py
> +    def test_GIVEN_PVONE_and_PVTWO_in_range_WHEN_in_range_value_written_THEN_no_alarm_and_value_written(self):
Could we have an additional test that when only one value is out of range there is no alarm and the value is written correctly

2020-11-12 14:31 UTC, DominicOram requested changes
These look good but I'm getting occasional errors of the form:
![image](https://user-images.githubusercontent.com/10086797/98952688-a511eb80-24f3-11eb-822b-ca9fb8f28152.png)

2020-11-24 12:12 UTC, DominicOram approved these changes
Errors were my fault, sorry

2020-11-24 12:28 UTC, merged