adding tests for wish ORC
ISISComputingGroup/EPICS-IOC_Test_Framework pull request #489
Opened 2021-10-01 10:00 UTC by rerpha

2021-10-04 15:16 UTC, DominicOram requested changes
Sorry, I know we talked about this already but I actually think it would be good to have them both using a shared file as there is quite a bit of repetition. Also, can we have some tests for the logic of working out the time until the next maintenance roattion?

2021-10-04 16:05 UTC, rerpha commented on tests/oscillating_collimator_wish.py
> +        self.ca = ChannelAccess(device_prefix=PREFIX)
They pass, it only speeds it up 10 times 😆

2021-10-04 17:10 UTC, rerpha commented on tests/oscillating_collimator_wish.py
> +        self.ca.assert_that_pv_is_number(ANGLE, 2.0)
yes they are, im not sure they are actually worth keeping regardless as the discriminant calc stuff is all covered in the parametrised test anyway

2021-10-05 10:52 UTC, DominicOram approved these changes
Great, thank you

2021-10-05 11:03 UTC, merged