Ticket6079 Aeroflex Tests
ISISComputingGroup/EPICS-IOC_Test_Framework pull request #572
Opened 2022-11-07 08:31 UTC by Scott-James-Hurley

Adds tests for the Aeroflex IOC. Similar in design to the Danfysik tests to allow for device switching. The tests cover getting and setting PVs as well as the calc records.

ISISComputingGroup/IBEX/issues/6079

2022-11-09 12:14 UTC, NikolaRoev requested changes
Issues suggested in my comments are in multiple tests.

These tests generally confirm that existing functionality works correctly. That's good but we need to check if the IOC will behave as we expect when things go wrong.

As an example there should be a test that sends a pulse on the 2030 in mode `AM`, will that test fail as expected?

From the ticket `There is also a 1500ms wait in the 2030 code when sending this value`, is that behaviour needed? If yes, there should be a test.

Should also probably add disconnection logic test, check out usage of `self._lewis.backdoor_simulate_disconnected_device`.

2022-11-09 12:14 UTC, NikolaRoev commented on common_tests/aeroflex.py
> +    @parameterized.expand([('Value 1', 1), ('Value 2', 2), ('Value 3', 3.33333)])
Do we need to check if the precision is handled correctly on the different devices?

2022-11-14 12:54 UTC, Scott-James-Hurley commented on common_tests/aeroflex.py
> +        self.ca.set_pv_value('CARRIER_FREQ', 1000)
This test checks that the carrier frequency value retrieved from the device (`CARRIER_FREQ` record) is correctly converted to the chosen units.

2022-11-14 12:59 UTC, Scott-James-Hurley commented on common_tests/aeroflex.py
> +        self.ca.assert_that_pv_is('CARRIER_FREQ:SP_NO_ACTION', 1.2)
I think it's useful as this assertion makes it easier to determine where an issue lies if the test fails. I'm fine with removing it, though.

2022-11-16 15:09 UTC, closed without merging