Ticket5872 Tests for Danfysik and RIKENFE PLC for RIKEN OPI
ISISComputingGroup/EPICS-IOC_Test_Framework pull request #579
Opened 2022-12-05 09:15 UTC by LowriJenkins

Added tests for changes made as part of https://github.com/ISISComputingGroup/IBEX/issues/5872
Ensure https://github.com/ISISComputingGroup/IBEX/issues/7241 is merged first as these are extensions to those tests.

2022-12-09 15:03 UTC, Tom-Willemsen requested changes

2022-12-14 12:33 UTC, LowriJenkins commented on tests/rikenfe_plc.py
> +        self.ca.set_pv_value("SIM:KICKER1:CURR",inpa)
the section of code quoted here already does reset the kickers to zero current?

2022-12-14 13:20 UTC, Tom-Willemsen commented on tests/rikenfe_plc.py
> +        self.ca.set_pv_value("SIM:KICKER1:CURR",inpa)
Sorry it looks like I have either got confused or missed a commit or something while reviewing this. Ignore this.

2022-12-15 14:49 UTC, Tom-Willemsen approved these changes

2022-12-15 14:49 UTC, merged